server:
  port: 8086

spring:
  application:
    name: ms-andesstay-rabbitmq-admin

rabbitmq:
  management-url: ${RABBITMQ_MANAGEMENT_URL:http://localhost:15672}
  management-username: ${RABBITMQ_USERNAME:guest}
  management-password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health,info
