server:
  port: 8083

spring:
  application:
    name: ms-andesstay-notify

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info
